@extends('layouts.app')
@section('title')
    Sejarah AKPI
@endsection
@section('content')
<div class="container body">
    <div class="row">
        @include('client.profile.sidemenu')
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title">Sejarah AKPI</h2>
                </div>
                <div class="panel-body">
                    <div class="detail-program">
                        <img src="{{ asset('dist/images/sejarah.jpg') }}" class="img-responsive mgb-md" alt="profil">
                        <p class="basic-text mgb-md">Pada awalnya Sang Pencipta menciptakan manusia sebagai makhluk sosial. Salah satu perwujudan manusia sebagai makhluk sosial adalah peradaban saling mendampingi dan menumbuhkan (mutual caring). Meskipun instinc saling membenci, memusuhi, dan membunuh (mutual killing) muncul dalam hidup manusia, namun mutual caring instinc jauh lebih kuat daripada mutual caring instinc. Peradaban mutual caring membuat keluarga universal manusia tetap eksis sampai Abad XXI. Dengan mutual caring di jaman apa pun hidupnya, di mana pun tinggalnya, apa pun asal etnisnya, apa pun warna kulitnya, dan kepercayaannya manusia saling mendampingi dan menumbuhkan. Dengan demikian secara proto-ilmah pendampingan dan konseling (termasuk konseling pastoral) memiliki sejarah panjang, setua usia manusia di bumi.</p>
                        <p class="basic-text mgb-md">Sebagai bagian integral keluarga manusia universal, komunitas Kristiani sesuai dengan sejarah dan pengalaman imannya mengembangkan mutual caring. Dalam sejarah komunitas Kristiani mutual caring disebut cura animarum atau care of the souls (penyembuhan jiwa). Ketika gereja mulai mencapai masa kejayaan, sejak Abad VII praktik cura animarum dilakukan oleh pemimpin (khususnya kaum tertahbis dan ordained) komunitas Kristiani yang disebut pastor dalam bahasa Latin atau gembala dalam bahasa Indonesia. Karena cura animarum dikaitkan dengan jabatan pastor atau gembala sebagai pemimpin umat, pada Awal XX di Amerika Serikat disebut sebagai pastoral care dan di Indonesia secara konvensional disebut sebagai penggembalaan. Sudah barang tentu sarana utama yang digunakan dalam pastoral care atau penggembalaan adalah bersifat gerejawi.</p>
                        <p class="basic-text mgb-md">Pada awal Abad XX sebagian pemimpin komunitas Kristiani Protestan merasa pendekatan pastoral care tradisional tidak mampu menjawab berbagai persoalan yang dialami oleh masyarakat Amerika Serikat yang sedang mengalami krisis kehidupan multidimensional yang sangat kompleks. Pada waktu yang sama psikologi dan disiplin terapannya konseling psikologi sedang mengalami perkembangan. Pada masa itu masyarakat Amerika Serikat mengalami "demam psikologi". Masyarakat Amerika Serikat berharap psikologi dan terapannya konseling psikologi dapat menjadi sarana untuk menangani krisis multidimensional dan kompleks tersebut. Seperti upaya ahli dalam disiplin lain, sebagian pemimpin komunitas Kristiani Protestan berupaya mengintegrasikan pastoral care tradisional dengan kearifan psikologi terapan: konseling psikologi. Kini usaha integrasi tersebut disebut konseling pastoral. Ada sebagian ahli dan praktisi konsisten mengintegrasikan pastoral care tradisional dengan pendekatan psikoanalitik Sigmund Freud dan menyebutnya sebagai psikoterapi pastoral.</p>
                        <p class="basic-text mgb-md">Konseling pastoral terus berkembang dan pada tahun 1950-an telah menjadi disiplin mandiri. Ketika itu di beberapa negara bagian Amerika Serikat, profesi konselor pastoral mendapat pengakuan sebagai profesi mandiri dan para praktisinya mendapat lisensi untuk praktik mandiri. Konseling pastoral juga telah mengembangkan standard pendidikan akademis yang dikelola oleh perguruan tinggi dan standard pendidikan/training profesi yang dikelola oleh asosisi profesi. Sebagian standard pendidikan/training profesi konselor pastoral tersebut tetap dipertahankan sampai masa sekarang. Puncak perkembangan konseling pastoral ditandai oleh berdirinya American Association of Pastoral Counselors (AAPC) pada bulan Maret 1963 (www.aapc.org). AAPC merupakan asosiasi konselor pastoral tertua, terkenal, terbesar, dan menjadi acuan asosiasi dan pendidikan profesi konselor pastoral secara global. Sebagaimana organisasi profesi konselor di negara lain, program utama Asosiasi Konselor Pastoral Indonesia (www.akpi-iapc.org) adalah pendidikan profesi konselor pastoral atau Pastoral Counselor Formation (PCF).</p>
                        <p class="basic-text mgb-md">Konseling pastoral terus mengalami perkembangan pesat, menyebar ke seluruh dunia dan masuk ke Indonesia pada awal 1980-an. Perkembangan konseling pastoral di Indonesia dimulai ketika Dr. Aart van Beek (www.parkviewpc.org) seorang utusan dari Presbyterian Church USA (kini menjadi Anggota Kehormatan AKPI) bersama Totok S. Wiryasaputra (kini Ketua Badan Pengurus Nasional AKPI) mengembangkan layanan konseling pastoral di RS Bethesda, Yogyakarta. Dari RS Bethesda, melalui layanan dan pelatihan secara berkala, pendampingan dan konseling pastoral menyebar ke seluruh Indonesia, khususnya melalui rumah-rumah sakit Kristiani. Setelah itu dengan berbagai namanya, layanan pendampingan dan konseling pastoral masuk ke berbagai rumah sakit lain. Pada masa kini hampir semua rumah sakit Kristen dan Katholik telah memiliki layanan pendampingan pastoral. Bahkan beberapa Sekolah Tinggi Teologi, Fakultas Teologi, Seminari telah membuka program pascasarjana konseling pastoral. Apabila kita melihat dari perspektif kuantitas perkembangan tersebut sangat menggembirakan, namun dari sisi kualitas tampaknya gerakan konseling pastoral di Indonesia sejak tahun 1980-an dekade pertama Abad XXI mengalami stagnasi.</p>
                        <p class="basic-text mgb-md">Mengingat perkembangan tersebut dan atas dorongan Bagian Layanan Pastoral Yayasan Kristen untuk Kesehatan Umum (YAKKUM) yang berpusat di Sala, Jawa Tengah, pada tahun 2011 Fakultas Teologi Universtas Kristen Satya Wacana (UKSW) Salatiga menjalin kerjasama dengan Persekutuan Kristen untuk Kesehatan di Indonesia (PELKESI) merintis Program Pendidikan Kompetensi Dasar Konselor Pastoral (PPKDKP) I. Pada akhirnya sembilan (9) lulusan, dua (2) peserta, dan supervisor klinis praktikum PPKDKP I bertempat di Graha Konseling Salatiga, pada 30 Juni 2012, pukul 10.10 WIB sepakat untuk menjadi pendiri dan mendirikan Asosiasi Konselor Pastoral Indonesia (AKPI). Kemudian PPKDKP I diteruskan dengan PPKDKP II pada tahun 2012 dan PPKDKP III pada tahun 2013. PPKDKP terdiri atas dua bagian, yakni Kuliah Intensif selama dua dan tiga minggu dan Praktikum Konseling 400 jam atau selama enam tiga sampai duabelas bulan. Karena pada awal 2014 Perjanjian Kerjasama Fakultas Teologi dan PELKESI tidak diteruskan lagi, AKPI berinisiatif untuk meneruskan PPKDKP dengan nama baru, yakni Pastoral Counselor Formation (PCF) pada tahun 2014 (Angkatan 04). Dalam perkembangannya pada tahun 2015 AKPI melakukan kerjasama dengan Sekolah Tinggi Diakones HKBP Balige, Sumatra Utara untuk mengadakan PCF. Dengan demikian sejak tahun 2015, AKPI memiliki dua (2) Program PCF (Angkatan 06 dan 07), yakni di Balige pada Minggu III dan IV Juni dan Salatiga pada Minggu III dan IV Agustus. Peserta Kuliah Intensif PCF berasal dari seluruh wilayah dan mewakili berbagai denominasi/aliran Kristiani di Indonesia. Bahkan satu orang dari komunitas Islam mengikuti PCF Angkatan 04 (2014) di Salatiga. AKPI melaksanakan PCF Angkatan 08 pada tanggal 18 dan 31 Agustus 2016 di Salatiga. Menurut rencana AKPI bekerjasama dengan Pusat Pastoral Yogyakarta akan melaksanakan PCF pada tahun 2017. Semoga akan banyak lembaga lain yang bekerjasama dengan AKPI untuk menjadi pusat-pusat pendidikan profesi konselor pastoral di Indonesia.</p>
                        <p class="basic-text mgb-md">Kini konselor pastoral AKPI tersebar di seluruh wilayah Indonesia dari Tanah Nias sampai Tanah Papua dan melakukan konseling pastoral dalam berbagai setting layanan, seperti perguruan tinggi, rumah sakit, sekolah, anak jalanan, panti wredha, panti pemulihan gangguan jiwa, pasien HIV/AIDS, human touch center, dan gereja/jemaat.</p>
                        <br>
                        <p>Salam <strong>VIVA AKPI</strong> dan <strong>VIVA konselor AKPI</strong> !!!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br><br>
@endsection
